### ISSUE TITLE
Update skeleton loader to use UI-kit

### ISSUE THREAD

**Issue by RitaMAllenCA** [casper-network/casper-blockexplorer#244]
doing this is dependent on the release of the ui-kit

**Comment by DorianKwan** [comment]
@RitaMAllenCA I believe there was a ticket for this already.  In any case -- I believe the approach for the skeleton loader needs to be discussed further.  Since it comes from a great package out of the box, I think we should just update all components that have integrated it in BE to the ui kit.  But maybe not directly re-export the package itself.

Not sure if that makes sense to you, I'd be happy to chat about it

**Comment by hoffmannjan** [comment]
Closing as won't do.
