### ISSUE TITLE
Re-Add PageWrapper & Navbar Tests

### ISSUE THREAD

**Issue by Thistle-Strum** [casper-network/casper-blockexplorer#289]
Add existing page wrapper test once ui bug in jest environment has been resolved

**Comment by DorianKwan** [comment]
Two tests were removed from the Casper Block Explorer: `Navbar.test.tsx` & `PageWrapper.test.tsx`. 
This was due to a bug within the Casper UI Kit that only occurred within the jest environment.  This has since been resolved in v0.5.2 that was released today.

This ticket is meant to bump the `casper-ui-kit` version to 0.5.2 and re-add the previously deleted tests
